### ISSUE TITLE
Starting nwggrid in sway  with tilling mode crashes the application

### ISSUE THREAD

**Issue by jasonthird** [nwg-piotr/nwg-launchers#121]
When i try to start nwggrid with "for_window [title="~nwg"] floating disable" (which for some reason was the default for my config) just makes nwggrid unresponsive and crashes after a while. 
The same behavior i can observe with sgtk-grid but in this case it just becomes unresponsive without crashing.

i don't think its a big issue but you might want to warn users using sway to just put in there config file "for_window [title="~nwg"] floating enable" so nwg-launchers work as expected.

I'm using arch Linux, installed both from the aur.

**Comment by jasonthird** [comment]
After going through the source code, i see that there is already a hacki solution to my problem file nwg-launchers/grid/grid.cc line 288 ` auto* cmd = "swaymsg for_window [title=\"~nwggrid*\"] floating enable";
`and for some reason i doesn't work on my system.
i might take a look at it in a few days and patch it

**Comment by nwg-piotr** [comment]
Well, I couldn't confirm neither crashes nor any other misbehavior after adding the `for_window [title="~nwg"] floating disable` rule. On my testing laptop it just works as expected. The swaymsg command executed from within the app seems to successfully override the rule in `config`.

I'm always open to contributions, but please keep in mind that:

1. The *hacki solution* has its justification: sway is the primary environment where `nwg-launchers` are expected to work, as well for power user, as for the rest. That's why I'd like to avoid making users add anything to their `config`.
2. `nwgrid` is intended to start as a fullscreened, semi-transparent window. On sway it's impossible to use the `Gtk::Window::fullscreen	()` method: **fullscreened window is always opaque on sway**. This forces us to make the window floating and resize it to the screen dimensions. *For another reason `.fullscreen()` is useless on i3, too*.

**Comment by nwg-piotr** [comment]
With no further feedback, I assume it's no longer an issue. Reopen if I'm wrong.
