### ISSUE TITLE
Windowed grid mode

### ISSUE THREAD

**Issue by UltimateOmega** [nwg-piotr/nwg-launchers#29]
is it possible to add windowed grid mode?

**Comment by nwg-piotr** [comment]
Many things are possible, but you need to be more specific. What exactly do you expect?

**Comment by UltimateOmega** [comment]
Right now I'm on arch with Openbox and Xorg. the the ability to control the width and height of grid menu would allow us to customize it even more , maybe even creating something like Slingshot Launcher from the elementary team.

**Comment by nwg-piotr** [comment]
Well, in sway it would need a change just in one line of code and one more argument. In Openbox you'd also need to pass initial window width and height. Otherwise, at least on my machine, the window dimensions are being forgotten on consecutive runs. Furthermore, it'll probably behave differently on other floating WMs. IMO such changes don't make much sense.
