### ISSUE TITLE
[Void Linux] nlohmann-json not found during compilation

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/nwg-launchers#45]
After @ericonr 's [comment](https://github.com/nwg-piotr/nwg-launchers/pull/35#issuecomment-655197737):

> I tested it in Void's build system, works well except for the system JSON library, which it can't find during cross compilation

Could it be corrected in Meson? @santouits

**Comment by santouits** [comment]
Do you have cmake installed? It seems to me the void packager of json-c++ only included the cmake file and not the pkgconfig too

**Comment by ericonr** [comment]
Hi! I managed to fix it using some weird CMake tricks, but it seems to be because meson doesn't support using CMake for cross without any external configuration, at least for now. Does json-c++ include pkg-config files? That would be much better.

**Comment by ericonr** [comment]
https://github.com/nlohmann/json/pull/1701 seems like it isn't yet, but I'll see if I can reopen that PR.

**Comment by santouits** [comment]
Do that but don't stress over it too much because it is just a header, there is no library to link, every program that builds with it will generate new code anyway.

**Comment by nwg-piotr** [comment]
I'm getting lost. Is it still an issue? I mean: is it possible to make a working Void template now?

**Comment by ericonr** [comment]
In the current situation, I can:

- Make everything work out of the box, without downloading the JSON library as a subproject, by hacking around Void's build system. It is ugly, and unlikely to be accepted.
- Make everything work  by simply adding the JSON library as a subproject. A bit bad, because it means it will require manual updates to the subproject, but it works cleanly. And since the library is header only, it isn't too big of an issue to use it as a subproject.
- Once/if my patch is accepted upstream for the JSON library, I can import it as a patch for Void, allowing me to use it without any hacks whatsoever.

It should be noted, this is only an issue for cross-compilation. For native compilation, everything is working great.

If you'd like to keep this issue open to track that progress, it is fine. But it's only relevant once we have a new release.

**Comment by nwg-piotr** [comment]
Yes, it would be great to have a Void package in repos. Lack of my favourite launchers is the main reason I haven't launched Void for a couple of weeks. :)

**Comment by ericonr** [comment]
Ok, my PR in the JSON repo has been accepted. Depending on the release schedule, I might have to patch it for Void, but being an upstream patch it should be fine.

**Comment by nwg-piotr** [comment]
Great news, thanks! I'll be able vacuum clean my Void install. :)

**Comment by ericonr** [comment]
https://github.com/void-linux/void-packages/pull/23592 :D

**Comment by nwg-piotr** [comment]
Fingers crossed. My last 2 commits were merged by Hoshpak in less than 24 hours. :)

**Comment by ericonr** [comment]
It's been accepted, so I guess we can close the issue :D

**Comment by nwg-piotr** [comment]
Well done! It means I'm in the Void tonight. :)

**Comment by nwg-piotr** [comment]
If only had I had `redshift-wayland` here, I'd feel comfortable on Void.

![sway-grid.png](https://scrot.cloud/images/2020/07/17/sway-grid.png)

**Comment by travankor** [comment]
@nwg-piotr 

```
git clone --depth 1 https://github.com/travankor/void-packages/ --single-branch --branch redshift-wayland
```

And then follow this: https://github.com/void-linux/void-packages#quick-start

**Comment by nwg-piotr** [comment]
@travankor many thanks!
